fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat'
    elasticsearch: 'https://github.com/elastic/puppet-elasticsearch'
    logstash: 'https://github.com/elastic/puppet-logstash'
  symlinks:
    elk: "#{source_dir}"
