fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    file_concat: 'https://github.com/electrical/puppet-lib-file_concat.git'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat'
    nginx: 'https://github.com/jfryman/puppet-nginx.git'
    apt: 'https://github.com/puppetlabs/puppetlabs-apt.git'
    yum: 'https://github.com/CERIT-SC/puppet-yum.git'
    datacat: 'https://github.com/richardc/puppet-datacat.git'
    elasticsearch: 'https://github.com/elastic/puppet-elasticsearch'
    logstash: 'https://github.com/elastic/puppet-logstash'
  symlinks:
    elk: "#{source_dir}"
