HOSTS:
  centos-6-x64:
    platform: el-6-x86_64
    hypervisor: docker
    image: centos:centos6
    docker_cmd: '["sh", "-c", "/sbin/service sshd start ; tail -f /dev/null"]'
    docker_preserve_image: true
CONFIG:
  type: foss
  log_level: verbose
